### ISSUE TITLE
error in squared_exp_kernel() calculation because the centers vector is empty

### ISSUE THREAD

**Issue by nickreich** [reichlab/ssr-influenza-competition#4]
Not sure what is causing this error, but using the current version I'm able to make predictions for up to 10 horizons, then it breaks at horizon 11 with this error:

```
Error in squared_exp_kernel(bw = 0.116765527674888, x = c(0.833499811462963,  :  center must be numeric with length 1
```

Any thoughts?

**Comment by nickreich** [comment]
Current version of code in flu-predictions-sandbox.R

**Comment by elray1** [comment]
fixed with code I just committed -- this was a bug I fixed somewhere before, didn't make it into this version of the code...............................

**Comment by nickreich** [comment]
Thanks!

## 

Nicholas G. Reich, Ph.D.
Assistant Professor
Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

413.545.4534
nick@schoolph.umass.edu
http://reichlab.github.io/
on twitter: @reichlab
