### ISSUE TITLE
Add a LICENSE.md

### ISSUE THREAD

**Issue by jg-you** [reichlab/ssr-influenza-competition#6]
I would like to distribute some of  the datasets added to this repository along with a new inference code I'm working on. 
I am of course giving credit, but I would also like to share the license for the original data, which there are none at the moment.

Could a LICENSE---say MIT--- be added?
I can put in a pull request.

**Comment by nickreich** [comment]
All of the raw influenza data are available from the proper source of the data,the US CDC. I recommend accessing through the cdcfluview R package: https://github.com/hrbrmstr/cdcfluview

If you are looking to use some of our forecasts or other analysis datasets specific to this repo, please feel free to add a MIT license. thanks.

**Comment by jg-you** [comment]
Alright, I'll use the fluview package then. Thanks for letting me know!
I went ahead and added a license anyways, just in case.
